### ISSUE TITLE
Provide as fontend compoent with bower

### ISSUE THREAD

**Issue by robinboehm** [L1fescape/curtsy#2]
Hey really cool project...
may you want to offer this via bower.io

If you need help, just ping me...

**Comment by L1fescape** [comment]
Thanks @robinboehm! Sounds like a good idea. I'll get cracking on it, then test it when I'm back from Thanksgiving vacation and have access to my Leap Motion again.

**Comment by robinboehm** [comment]
Cool.
You just need a configuration file in json format.
:+1: 

ProTip: Choose name wisely, its a mess to remove it from the register after added it once! :)

**Comment by 0x-r4bbit** [comment]
Hey @L1fescape How about merging forces with us? Maybe you're interested in angular-leap https://github.com/angular-leap/angular-leap

**Comment by L1fescape** [comment]
@PascalPrecht possibly! I haven't done much with Angular but it looks like you guys are working on some cool stuff.

**Comment by L1fescape** [comment]
Hey @robinboehm bower support has been added! You can now install curtsy via `bower install curtsy`.

Is there any advice you could give or tweaks I should make for having a package work with both bower and node?

**Comment by 0x-r4bbit** [comment]
@L1fescape If it should work with node (or actually npm) you have to register the code as npm module. If your code should work environment independent, well.. it shouldn't depend on any environment features. I think making it available via bower is enough at a first glance.

**Comment by L1fescape** [comment]
@PascalPrecht I registered curtsy with npm a few months ago and you can check it out here: https://npmjs.org/package/curtsy

Just curious if there were any quirks/best practices of registering a package with both npm and bower.

**Comment by L1fescape** [comment]
Closing this ticket since bower has been added with 0f368a3817af01ca67dc648a8c3f32a2b689e1c8

**Comment by robinboehm** [comment]
:+1:

Thx @L1fescape !
